### PR TITLE
Better JavaScript

### PR DESCRIPTION
**Pull request by diogoscf**
If you ever screw up the JS again:

run `eslint FILE`
(make sure you have eslint installed ofc)

### CODE REVIEW

**Comment by aadibajpai** [comment]
what does that eslinter thing do and what exactly has changed?

**Comment by aadibajpai** [comment]
> If you ever screw up the JS again:
> 
> run `eslint FILE`
> (make sure you have eslint installed ofc)

is there a github action or something? like on python I use pep8speaks

**Comment by aadibajpai** [comment]
I think it doesn't deal with localstorage very well
image
image

**Comment by diogoscf** [comment]
> what does that eslinter thing do and what exactly has changed?

Just coding style. `eslint` is a linter for JavaScript, and the `.eslintrc.json` file provides the specific rules for the linter

> is there a github action or something? like on python I use pep8speaks

I've never personally used it, but there's this: https://github.com/marketplace/actions/eslint-action
I have used HoundCI in the past, which has eslint integration, but it only works on PRs

**Comment by aadibajpai** [comment]
> > what does that eslinter thing do and what exactly has changed?
> 
> Just coding style. `eslint` is a linter for JavaScript, and the `.eslintrc.json` file provides the specific rules for the linter
> 
> > is there a github action or something? like on python I use pep8speaks
> 
> I've never personally used it, but there's this: https://github.com/marketplace/actions/eslint-action
> I have used HoundCI in the past, which has eslint integration, but it only works on PRs

hmm I guess makes more sense to do it manually then

**Comment by diogoscf** [comment]
> I think it doesn't deal with localstorage very well

hmmm weird, are you sure this is new from this PR?

**Comment by diogoscf** [comment]
ah wait nvm I know why it's happening

**Comment by aadibajpai** [comment]
looks good, thank you! <3

If you're interested in joining ABSPP, send your application at clash at hey dot com

**Pull request merged**
